### ISSUE TITLE
For REVIEW

### ISSUE THREAD

**Issue by Itswali** [Itswali/Rental-Cars#16]
### There are 4 People in this Team.

@Itswali  @kwesiObuobi  @DJ-MrJay  @r-ahmed2022 

[The LInk To Kanban Board](https://github.com/users/Itswali/projects/12/views/1)

In this project, we are going to build the Final Capstone Project based on an app for reserving Bikes

- [ ] Kanban Board Screen Shot Below
![image](https://github.com/Itswali/Rental-Bikes/assets/104720431/4d18be72-4d0d-44f6-bb01-cd716dff0987)

**Comment by Meltrust** [comment]
Hi @Itswali,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have been assigned, have descriptions and have fair pointings ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
